
#List of affix configurations
[[affixes]]
	identifier = "adaptable"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 3
	enabled = true

[[affixes]]
	identifier = "arctic"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "dampening"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "desecrating"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 4
	enabled = true

[[affixes]]
	identifier = "enkindling"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "hasty"
	mobList = []
	maxTier = 5
	mobPermission = "BLACKLIST"
	minTier = 2
	enabled = true

[[affixes]]
	identifier = "infested"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 2
	enabled = true

[[affixes]]
	identifier = "knocking"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "lively"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "magnetic"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 7
	enabled = false

[[affixes]]
	identifier = "molten"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 7
	enabled = true

[[affixes]]
	identifier = "paralyzing"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 2
	enabled = true

[[affixes]]
	identifier = "plagued"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 7
	enabled = true

[[affixes]]
	identifier = "reflective"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 4
	enabled = true

[[affixes]]
	identifier = "shielding"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 7
	enabled = false

[[affixes]]
	identifier = "wounding"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

